<a href="https://colab.research.google.com/github/tomarayush8624/AI-ML/blob/main/AI_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import numpy
import pandas as pd

In [ ]:
arr = numpy.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [ ]:
arr = numpy.array([[1, 2, 3, 4],[2, 3, 4, 5]])
arr

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [ ]:
numpy.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
newarr = arr.reshape(-1)
newarr

array([1, 2, 3, 4, 2, 3, 4, 5])

In [ ]:
temp = numpy.array([1, 2, 3, 4, 5, 6])
arr1 = temp.reshape(2, 3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2 = np.zeros(5, dtype=int)
arr2

array([0, 0, 0, 0, 0])

In [ ]:
arr2 = np.ones(5)

In [ ]:
arr2 = np.empty([4, 2])
arr2

array([[ 7.       , 27.       ],
       [15.1217283,  6.       ],
       [16.5      , 27.       ],
       [37.5      , 48.       ]])

In [ ]:
arrTemp = np.array([2, 6, 4, 5])

In [ ]:
arrTemp.sort()
arrTemp

array([2, 4, 5, 6])

In [ ]:
arr2 = np.array([2, 5, 6, 2 , 7])
arr3 = np.concatenate((arrTemp, arr2))
arr3
# arr2

array([2, 4, 5, 6, 2, 5, 6, 2, 7])

In [ ]:
print(arr2 )
print(arr2[0: 3])
print(arr2[1:])
print(arr2[-3:])
print(arr2[arr2 > 2])

[2 5 6 2 7]
[2 5 6]
[5 6 2 7]
[6 2 7]
[5 6 7]


In [ ]:
print(arr2 + arr2)
print(arr2 * arr2)

[ 4 10 12  4 14]
[ 4 25 36  4 49]


In [ ]:
print(arr2.sum())
print(arr2.max())
print(arr2.min())

22
7
2


In [ ]:
arr4 = np.arange(49).reshape(7, 7)
arr4

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [ ]:
df1 = pd.DataFrame(data=arr4)
df1

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
5  35  36  37  38  39  40  41
6  42  43  44  45  46  47  48

In [ ]:
print(type(df1))
print(df1.dtypes)

<class 'pandas.core.frame.DataFrame'>
0    int64
1    int64
2    int64
3    int64
4    int64
5    int64
6    int64
dtype: object


In [ ]:
print(df1.describe())

               0          1          2          3          4          5  \
count   7.000000   7.000000   7.000000   7.000000   7.000000   7.000000   
mean   21.000000  22.000000  23.000000  24.000000  25.000000  26.000000   
std    15.121728  15.121728  15.121728  15.121728  15.121728  15.121728   
min     0.000000   1.000000   2.000000   3.000000   4.000000   5.000000   
25%    10.500000  11.500000  12.500000  13.500000  14.500000  15.500000   
50%    21.000000  22.000000  23.000000  24.000000  25.000000  26.000000   
75%    31.500000  32.500000  33.500000  34.500000  35.500000  36.500000   
max    42.000000  43.000000  44.000000  45.000000  46.000000  47.000000   

               6  
count   7.000000  
mean   27.000000  
std    15.121728  
min     6.000000  
25%    16.500000  
50%    27.000000  
75%    37.500000  
max    48.000000  


In [ ]:
df1.tail(3)

0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
5  35  36  37  38  39  40  41
6  42  43  44  45  46  47  48

In [ ]:
df2 = pd.DataFrame(data=arr4, index=['r1', "r2", 'r3', 'r4', 'r5', 'r6', 'r7'], columns=['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7'])
df2

c1  c2  c3  c4  c5  c6  c7
r1   0   1   2   3   4   5   6
r2   7   8   9  10  11  12  13
r3  14  15  16  17  18  19  20
r4  21  22  23  24  25  26  27
r5  28  29  30  31  32  33  34
r6  35  36  37  38  39  40  41
r7  42  43  44  45  46  47  48

In [ ]:
df2.loc['r2':'r4', "c2"]

r2     8
r3    15
r4    22
Name: c2, dtype: int64

In [ ]:
print(df2.loc[df2['c2'] > 25])

    c1  c2  c3  c4  c5  c6  c7
r5  28  29  30  31  32  33  34
r6  35  36  37  38  39  40  41
r7  42  43  44  45  46  47  48


In [ ]:
df1.loc[1]

0     7
1     8
2     9
3    10
4    11
5    12
6    13
Name: 1, dtype: int64

In [ ]:
df2.iloc[2, 3] = 'NaN'
print(df2)

    c1  c2  c3   c4  c5  c6  c7
r1   0   1   2    3   4   5   6
r2   7   8   9   10  11  12  13
r3  14  15  16  NaN  18  19  20
r4  21  22  23   24  25  26  27
r5  28  29  30   31  32  33  34
r6  35  36  37   38  39  40  41
r7  42  43  44   45  46  47  48


In [ ]:
df2.isnull()

c1     c2     c3     c4     c5     c6     c7
r1  False  False  False  False  False  False  False
r2  False  False  False  False  False  False  False
r3  False  False  False  False  False  False  False
r4  False  False  False  False  False  False  False
r5  False  False  False  False  False  False  False
r6  False  False  False  False  False  False  False
r7  False  False  False  False  False  False  False

In [ ]:
df2.iloc[0:, 0:]

c1  c2  c3   c4  c5  c6  c7
r1   0   1   2    3   4   5   6
r2   7   8   9   10  11  12  13
r3  14  15  16  NaN  18  19  20
r4  21  22  23   24  25  26  27
r5  28  29  30   31  32  33  34
r6  35  36  37   38  39  40  41
r7  42  43  44   45  46  47  48

In [ ]:
df2['c2'].max()

43

In [ ]:
df2['c2'].mean()

22.0

In [ ]:
df2['c2'].std()

15.121728296285006

In [ ]:
df2[tf]

NameError: name 'tf' is not defined

# Working with CSV


In [ ]:
df3 = pd.read_csv('titanic.csv')

In [ ]:
df3

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
df3[df3['Age'] > 60]

PassengerId  Survived  Pclass                                       Name  \
33            34         0       2                      Wheadon, Mr. Edward H   
54            55         0       1             Ostby, Mr. Engelhart Cornelius   
96            97         0       1                  Goldschmidt, Mr. George B   
116          117         0       3                       Connors, Mr. Patrick   
170          171         0       1                  Van der hoef, Mr. Wyckoff   
252          253         0       1                  Stead, Mr. William Thomas   
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
280          281         0       3                           Duane, Mr. Frank   
326          327         0       3                  Nysveen, Mr. Johan Hansen   
438          439         0       1                          Fortune, Mr. Mark   
456          457         0       1                  Millet, Mr. Francis Davis   
483          484         1       3                     Turkula, Mrs. (Hedwig)   
493          494         0       1                    Artagaveytia, Mr. Ramon   
545          546         0       1               Nicholson, Mr. Arthur Ernest   
555          556         0       1                         Wright, Mr. George   
570          571         1       2                         Harris, Mr. George   
625          626         0       1                      Sutton, Mr. Frederick   
630          631         1       1       Barkworth, Mr. Algernon Henry Wilson   
672          673         0       2                Mitchell, Mr. Henry Michael   
745          746         0       1               Crosby, Capt. Edward Gifford   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   
851          852         0       3                        Svensson, Mr. Johan   

        Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked  
33     male  66.0      0      0   C.A. 24579   10.5000          NaN        S  
54     male  65.0      0      1       113509   61.9792          B30        C  
96     male  71.0      0      0     PC 17754   34.6542           A5        C  
116    male  70.5      0      0       370369    7.7500          NaN        Q  
170    male  61.0      0      0       111240   33.5000          B19        S  
252    male  62.0      0      0       113514   26.5500          C87        S  
275  female  63.0      1      0        13502   77.9583           D7        S  
280    male  65.0      0      0       336439    7.7500          NaN        Q  
326    male  61.0      0      0       345364    6.2375          NaN        S  
438    male  64.0      1      4        19950  263.0000  C23 C25 C27        S  
456    male  65.0      0      0        13509   26.5500          E38        S  
483  female  63.0      0      0         4134    9.5875          NaN        S  
493    male  71.0      0      0     PC 17609   49.5042          NaN        C  
545    male  64.0      0      0          693   26.0000          NaN        S  
555    male  62.0      0      0       113807   26.5500          NaN        S  
570    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S  
625    male  61.0      0      0        36963   32.3208          D50        S  
630    male  80.0      0      0        27042   30.0000          A23        S  
672    male  70.0      0      0   C.A. 24580   10.5000          NaN        S  
745    male  70.0      1      1    WE/P 5735   71.0000          B22        S  
829  female  62.0      0      0       113572   80.0000          B28      NaN  
851    male  74.0      0      0       347060    7.7750          NaN        S

In [ ]:
df3['Age'].mean()

29.69911764705882

In [ ]:
df3[df3['Age'] > 60].mean()

<ipython-input-131-5dba2ce4cf4c>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df3[df3['Age'] > 60].mean()


PassengerId    432.545455
Survived         0.227273
Pclass           1.590909
Age             66.022727
SibSp            0.136364
Parch            0.272727
Fare            41.371214
dtype: float64

In [ ]:
df3[df3['Survived'] == 1].count()

PassengerId    342
Survived       342
Pclass         342
Name           342
Sex            342
Age            290
SibSp          342
Parch          342
Ticket         342
Fare           342
Cabin          136
Embarked       340
dtype: int64

In [ ]:
df3.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

# Dictionary Modification


In [ ]:
students={
    'id':['1','2','3'],
    'Name':['Ayush','arnav','Shivansh'],
    'Gmail':['bc@gmail.com','abc@gmail.com','abc@gmail.com'],
    'Marks':['1','2','3']
    }

In [ ]:
df4 = pd.DataFrame(data=students)

In [ ]:
df4

id      Name          Gmail Marks
0  1     Ayush   bc@gmail.com     1
1  2     arnav  abc@gmail.com     2
2  3  Shivansh  abc@gmail.com     3

In [ ]:
df4 = df4.set_index('Gmail')
df4

id      Name Marks
Gmail                           
bc@gmail.com   1     Ayush     1
abc@gmail.com  2     arnav     2
abc@gmail.com  3  Shivansh     3

In [ ]:
df4['age'] = ["10", "40", "50"]
df4

id      Name Marks age
Gmail                               
bc@gmail.com   1     Ayush     1  10
abc@gmail.com  2     arnav     2  40
abc@gmail.com  3  Shivansh     3  50

In [ ]:
df4.sort_index(ascending=False)
# df4

id      Name Marks age
Gmail                               
bc@gmail.com   1     Ayush     1  10
abc@gmail.com  2     arnav     2  40
abc@gmail.com  3  Shivansh     3  50

In [ ]:
df4.rename(columns={'name': 'new_name'})

id      Name Marks age
Gmail                               
bc@gmail.com   1     Ayush     1  10
abc@gmail.com  2     arnav     2  40
abc@gmail.com  3  Shivansh     3  50

In [ ]:
df4.columns=[x.upper() for x in df4.columns]

In [ ]:
df4.apply(len)

ID       3
NAME     3
MARKS    3
AGE      3
dtype: int64

In [ ]:
df4.reset_index(inplace=True)

In [ ]:
df4

Gmail ID      NAME MARKS AGE
0   bc@gmail.com  1     Ayush     1  10
1  abc@gmail.com  2     arnav     2  40
2  abc@gmail.com  3  Shivansh     3  50

In [ ]:
df4 = df4.drop([3])

KeyError: '[3] not found in axis'

In [ ]:
df4.applymap(str.lower)

Gmail ID      NAME MARKS AGE
0   bc@gmail.com  1     ayush     1  10
1  abc@gmail.com  2     arnav     2  40
2  abc@gmail.com  3  shivansh     3  50

In [ ]:
df4

Gmail ID      NAME MARKS AGE
0   bc@gmail.com  1     Ayush     1  10
1  abc@gmail.com  2     arnav     2  40
2  abc@gmail.com  3  Shivansh     3  50

In [ ]:
len(df4['NAME'])

3

In [ ]:
df4.loc[2, ['NAME']] = 'rajj'

In [ ]:
df4

Gmail ID   NAME MARKS AGE
0   bc@gmail.com  1  Ayush     1  10
1  abc@gmail.com  2  arnav     2  40
2  abc@gmail.com  3   rajj     3  50

In [ ]:
df4.applymap(len)

Gmail  ID  NAME  MARKS  AGE
0     12   1     5      1    2
1     13   1     5      1    2
2     13   1     4      1    2

In [ ]:
df4['NAME'] + ' ' + df4['MARKS']

0    Ayush 1
1    arnav 2
2     rajj 3
dtype: object

In [ ]:
df4['new'] = df4['NAME'] + ' ' + df4['MARKS']
df4

Gmail ID   NAME MARKS AGE      new
0   bc@gmail.com  1  Ayush     1  10  Ayush 1
1  abc@gmail.com  2  arnav     2  40  arnav 2
2  abc@gmail.com  3   rajj     3  50   rajj 3

In [ ]:
df4['new'].str.split('')

0    [, A, y, u, s, h,  , 1, ]
1    [, a, r, n, a, v,  , 2, ]
2       [, r, a, j, j,  , 3, ]
Name: new, dtype: object

# Operations On dataframes

In [ ]:
students1={
    'id':['4','5','6'],
    'Name':['Ayush','arnav','Shivansh'],
    'Gmail':['bc@gmail.com','abc@gmail.com','abc@gmail.com'],
    'Marks':['1','2','3']
    }

In [ ]:
df5 = pd.DataFrame(data=students1)

In [ ]:
df6 = df4.append(df5)

<ipython-input-29-d700ca639778>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df6 = df4.append(df5)


In [ ]:
df6

Gmail   ID   NAME MARKS  AGE      new   id      Name Marks
0   bc@gmail.com    1  Ayush     1   10  Ayush 1  NaN       NaN   NaN
1  abc@gmail.com    2  arnav     2   40  arnav 2  NaN       NaN   NaN
2  abc@gmail.com    3   rajj     3   50   rajj 3  NaN       NaN   NaN
0   bc@gmail.com  NaN    NaN   NaN  NaN      NaN    4     Ayush     1
1  abc@gmail.com  NaN    NaN   NaN  NaN      NaN    5     arnav     2
2  abc@gmail.com  NaN    NaN   NaN  NaN      NaN    6  Shivansh     3

In [ ]:
df6.sort_values(by=['Marks', 'Name'], ascending=[False, True])

Gmail   ID   NAME MARKS  AGE      new   id      Name Marks
2  abc@gmail.com  NaN    NaN   NaN  NaN      NaN    6  Shivansh     3
1  abc@gmail.com  NaN    NaN   NaN  NaN      NaN    5     arnav     2
0   bc@gmail.com  NaN    NaN   NaN  NaN      NaN    4     Ayush     1
0   bc@gmail.com    1  Ayush     1   10  Ayush 1  NaN       NaN   NaN
1  abc@gmail.com    2  arnav     2   40  arnav 2  NaN       NaN   NaN
2  abc@gmail.com    3   rajj     3   50   rajj 3  NaN       NaN   NaN

In [ ]:
df5.applymap(len)

id  Name  Gmail  Marks
0   1     5     12      1
1   1     5     13      1
2   1     8     13      1

In [ ]:
df5.to_json()

'{"id":{"0":"4","1":"5","2":"6"},"Name":{"0":"Ayush","1":"arnav","2":"Shivansh"},"Gmail":{"0":"bc@gmail.com","1":"abc@gmail.com","2":"abc@gmail.com"},"Marks":{"0":"1","1":"2","2":"3"}}'